"""
Recommendation service — business logic layer.

Bridges the API controllers (main.py) and the model layer (als_model.py).
All Spark operations and data-enrichment happen here so that main.py stays thin.
"""

import json
import logging
import os
from typing import Any, Dict, List, Tuple

from app.model.als_model import get_model, get_restaurants_lookup, get_spark
from app.config import TOP_RESTAURANTS_PATH

logger = logging.getLogger(__name__)

def _enrich(restaurant_id: int, predicted_rating: float) -> Dict[str, Any]:
    """
    Look up restaurant metadata for a given integer restaurant_id and merge
    it with the ALS-predicted rating into a flat response dict.
    """
    lookup = get_restaurants_lookup()
    meta   = lookup.get(restaurant_id, {})
    return {
        'restaurantId':     restaurant_id,
        'name':             meta.get('name',           'Unknown'),
        'cuisine':          meta.get('cuisine',        'Restaurant'),
        'location':         meta.get('location',       'Colombo'),
        'price_range':      meta.get('price_range',    'Unknown'),
        'predicted_rating': round(predicted_rating, 4),
        'busyness_score':   meta.get('busyness_score', 0.0),
    }


def _top_rated_fallback(limit: int) -> List[Dict[str, Any]]:
    """
    Return the top-rated restaurants from the in-memory lookup.
    Used as a cold-start fallback when a user_id was not seen during training.
    """
    lookup = get_restaurants_lookup()
    ranked = sorted(
        lookup.items(),
        key=lambda kv: (kv[1].get('rating', 0.0), kv[1].get('total_ratings', 0)),
        reverse=True,
    )
    return [
        {
            'restaurantId':     rid,
            'name':             meta.get('name',           'Unknown'),
            'cuisine':          meta.get('cuisine',        'Restaurant'),
            'location':         meta.get('location',       'Colombo'),
            'price_range':      meta.get('price_range',    'Unknown'),
            # Use actual Google rating as predicted_rating for cold-start responses
            'predicted_rating': round(meta.get('rating', 0.0), 4),
            'busyness_score':   meta.get('busyness_score', 0.0),
        }
        for rid, meta in ranked[:limit]
    ]


# ── Public service functions ───────────────────────────────────────────────────

def fetch_recommendations(
    user_id: int,
    top_n: int = 10,
) -> Tuple[List[Dict[str, Any]], bool]:
    """
    Generate top_n restaurant recommendations for user_id.

    Cold-start handling
    -------------------
    If user_id was not seen during ALS training the model returns an empty
    result set.  In that case we transparently fall back to the top-rated
    restaurants so the caller always receives useful results.

    Returns
    -------
    (recommendations, is_cold_start)
        recommendations : list of enriched restaurant dicts
        is_cold_start   : True when the fallback path was taken
    """
    spark = get_spark()
    model = get_model()

    # Use spark.sql() with an integer literal — avoids Python→JVM pickle entirely.
    # spark.createDataFrame([(user_id,)], ...) always goes through the Python RDD
    # pickle path and raises RecursionError on Python 3.12+.
    user_df = spark.sql(f"SELECT CAST({int(user_id)} AS INT) AS userId")

    recs_rows = (
        model.recommendForUserSubset(user_df, numItems=top_n)
        .collect()
    )

    # Cold-start: ALS returned no rows for this user
    if not recs_rows:
        logger.info('Cold-start for user_id=%d — returning top-rated fallback.', user_id)
        return _top_rated_fallback(top_n), True

    raw_recs = recs_rows[0]['recommendations']   # list of Row(restaurantId, rating)

    results = sorted(
        [_enrich(int(rec['restaurantId']), float(rec['rating'])) for rec in raw_recs],
        key=lambda r: r['predicted_rating'],
        reverse=True,
    )
    return results, False


def fetch_top_restaurants(limit: int = 20) -> List[Dict[str, Any]]:
    """
    Return the pre-computed list of most-reviewed restaurants.

    Reads from top_restaurants.json (generated by train_and_save.py).
    Serving a static JSON file avoids a Spark job on every request.
    """
    if not os.path.exists(TOP_RESTAURANTS_PATH):
        raise FileNotFoundError(
            f'top_restaurants.json not found at {TOP_RESTAURANTS_PATH}. '
            'Run `./run.sh --train` first.'
        )
    with open(TOP_RESTAURANTS_PATH) as f:
        all_restaurants = json.load(f)
    return all_restaurants[:limit]


def fetch_restaurants(cuisine=None, district=None, price_range=None,
                      min_rating=None, sort_by='rating', limit=50):
    """Delegate to repository layer."""
    from app.repositories.restaurant_repo import query_restaurants
    return query_restaurants(
        get_spark(),
        cuisine=cuisine, district=district, price_range=price_range,
        min_rating=min_rating, sort_by=sort_by, limit=limit,
    )


def fetch_trending_analytics() -> Dict[str, Any]:
    """
    Use Spark SQL on the 'restaurants' temp view to compute:

    top_cuisines  — top 5 cuisines by restaurant count and average Google rating
    busiest_areas — top 5 Colombo areas by average synthetic busyness score

    The temp view is registered at startup from colombo_restaurants.csv so
    this function triggers a Spark job (results are small and fast to compute).
    """
    spark = get_spark()

    # ── Top 5 cuisines ────────────────────────────────────────────────────────
    # Exclude the generic 'Restaurant' label so results show specific cuisines.
    top_cuisines_rows = spark.sql("""
        SELECT
            cuisine,
            COUNT(*)             AS restaurant_count,
            ROUND(AVG(rating), 2) AS avg_rating
        FROM restaurants
        WHERE cuisine != 'Restaurant'
          AND cuisine IS NOT NULL
          AND rating  IS NOT NULL
        GROUP BY cuisine
        ORDER BY restaurant_count DESC, avg_rating DESC
        LIMIT 5
    """).collect()

    # ── Top 5 busiest areas ───────────────────────────────────────────────────
    busiest_areas_rows = spark.sql("""
        SELECT
            location,
            COUNT(*)                   AS restaurant_count,
            ROUND(AVG(busyness_score), 1) AS avg_busyness_score,
            ROUND(AVG(rating), 2)      AS avg_rating
        FROM restaurants
        WHERE location       IS NOT NULL
          AND busyness_score IS NOT NULL
        GROUP BY location
        ORDER BY avg_busyness_score DESC
        LIMIT 5
    """).collect()

    return {
        'top_cuisines': [
            {
                'cuisine':          row['cuisine'],
                'restaurant_count': int(row['restaurant_count']),
                'avg_rating':       float(row['avg_rating']),
            }
            for row in top_cuisines_rows
        ],
        'busiest_areas': [
            {
                'location':           row['location'],
                'restaurant_count':   int(row['restaurant_count']),
                'avg_busyness_score': float(row['avg_busyness_score']),
                'avg_rating':         float(row['avg_rating']),
            }
            for row in busiest_areas_rows
        ],
    }
